### ISSUE TITLE
 Error: h is not defined

### ISSUE THREAD

**Issue by sinchang** [zcong1993/template-react#2]
脚手架安装之后会出现  h is not defined 错误，升级到最新的 poi 可解决。

升级之后出现的问题是 poi-preset-eslint-react 出现  `poi.mode is not a function `

解决办法是：
poi-preset-eslint-react/index.js 33 行改成
```
poi.isMode()
```

**Comment by zcong1993** [comment]
抱歉, 最近比较忙, 麻烦提交个 pr, 谢谢

**Comment by zcong1993** [comment]
fixed
